### ISSUE TITLE
BGP listen address not editable

### ISSUE THREAD

**Issue by netfreak98** [natesales/bcg#10]
Would it be please possible to add an "listen address" option for the peer configuration?

In my setup I'm using OSPF to distribute loopback addresses which are used to establish the bgp sessions as well as a general routing target.

Default config which is not working:
```
protocol bgp IBGP_ROUTE_REFLECTORv4_0 {
    local as ASN;
    neighbor 185.121.69.151 as 49697;
    description "AS49697 IBGP ROUTE REFLECTOR";
    rr client;
```

Config which works after adding the local listen address manualy:
```
protocol bgp IBGP_ROUTE_REFLECTORv4_0 {
    local 185.121.69.149 as ASN;
    neighbor 185.121.69.151 as 49697;
    description "AS49697 IBGP ROUTE REFLECTOR";
    rr client;
```
```
root@c01:/etc/bcg# birdc show route all protocol IBGP_ROUTE_REFLECTORv4_0
[..]
45.139.220.0/24      unreachable [IBGP_ROUTE_REFLECTORv4_0 2021-04-27 20:20:52 from 185.121.69.151] * (100/-) [AS51559i]
        Type: BGP univ
        BGP.origin: IGP
        BGP.as_path: 3223 51559
        BGP.next_hop: 185.121.69.144
        BGP.med: 90
        BGP.local_pref: 100
        BGP.community: (49697,2000) (49697,2010) (49697,2402)
        BGP.originator_id: 185.121.69.2
        BGP.cluster_list: 185.121.69.151
        BGP.large_community: (49697, 0, 102)
```
(it's of cause UNREACHABLE cause BIRD is not synced with the kernel table yet which holds the routes injected by zebra)

OSPF (currently realized using FRR):
```
root@c01:/etc/bcg# ip r
[..]
185.121.69.144 nhid 36 via 185.121.69.130 dev vlan3001 proto ospf metric 20
```

**Comment by natesales** [comment]
This would indeed be a useful feature! 

The limitation here is that each peer block can contain an arbitrary number of BGP neighbor addresses, of either or both IPv4 and IPv6:

```yaml
peers:
  Cloudflare:
    asn: 13335
    type: peer
    neighbors:
      - 203.0.113.39
      - 2001:db8::39
      - 2001:db8::40
```

That of course wouldn't work with an explicit listen address of a single address family. I've added the `listen` key in 7d529ee51fd515aa2b4e3bdcc09ac2b98f0d685d, so you can now set the listen address under the peer block. Just keep in mind that if you do set a listen address, all neighbor addresses will have to be of the same address family.
