### ISSUE TITLE
Downstreams without PeeringDB record

### ISSUE THREAD

**Issue by netfreak98** [natesales/bcg#12]
For some reason there are still peers without a PeeringDB record.
In my case I already contacted the maintainer to create a record but BCP does not allow to procceed in such situation:

Example config:

```
  TEST PEER:
    asn: 208476
    as-set: AS208476
    import-limit4: 1
    local-pref: 500
    type: downstream
    neighbors:
      - "185.1.184.13"
```

```
root@e01:/etc/bcg# bcg --no-configure --verbose
[..]
INFO[0000] Checking config for TEST PEER AS208476
FATA[0000] Peer 208476 doesn't have a valid PeeringDB entry. Try import-valid or ask the network to update their account.
```
But since it's a downstream which prefixes I want to export to my upstreams and peers I just can't use "import-valid" as a peer-type. Even using the aut-num object in the RIR database it is possible to fetch allowed prefixes. In combination with an import limit in the config this should work without PeeringDB :D

Can you please adjust this line:
`func getPeeringDbData(asn uint) PeeringDbData`
in bcg/main.go to allow to continue please? :)

Thanks!
Joey

**Comment by natesales** [comment]
Sure, added the `no-peeringdb` option in `598b1241aa111f844dd6a51bbf3fc35fd721fd57`
